/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patch;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gadea
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnUrl = new javax.swing.JButton();
        lblSizeRect = new javax.swing.JLabel();
        lblwxh = new javax.swing.JLabel();
        lblx = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblNGroups = new javax.swing.JLabel();
        txtNGroups = new javax.swing.JTextField();

        lblUrl.setText("Url Results:");

        btnUrl.setText("Browse");
        btnUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrlActionPerformed(evt);
            }
        });

        lblSizeRect.setText("Size of Rectangle (pixels):");

        lblwxh.setText("width x height ");

        lblx.setText("x");

        txtWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWidth.setText("256");

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText("256");

        lblNGroups.setText("How many groups want to do?");

        txtNGroups.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUrl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSizeRect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblwxh))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNGroups)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrl)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSizeRect)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblwxh)
                    .addComponent(lblx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGroups)
                    .addComponent(txtNGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrlActionPerformed
        int result;
        JFileChooser chooser = new JFileChooser();

        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Browse");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); //only open directories
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String dir = (chooser.getSelectedFile()).getPath();
            txtUrl.setText(dir);
        }
    }//GEN-LAST:event_btnUrlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUrl;
    private javax.swing.JLabel lblNGroups;
    private javax.swing.JLabel lblSizeRect;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblwxh;
    private javax.swing.JLabel lblx;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtNGroups;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

//properties (get&set)
    public String getTxtUrl() {
        return this.txtUrl.getText();
    }
    public int getTxtWidth() {
        return Integer.parseInt(this.txtWidth.getText());
    }

    public int getTxtHeight() {
        return Integer.parseInt(this.txtHeight.getText());
    }

    public int getTxtNGroups()
    {
        return Integer.parseInt(this.txtNGroups.getText());
    }
}
