/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patch;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gadea
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnUrl = new javax.swing.JButton();
        lblSizeRect = new javax.swing.JLabel();
        lblwxh = new javax.swing.JLabel();
        lblx = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblNGroups = new javax.swing.JLabel();
        txtNGroups = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        rbtnSquare = new javax.swing.JRadioButton();
        rbtnScaled = new javax.swing.JRadioButton();

        lblUrl.setText("Url Results:");

        btnUrl.setText("Browse");
        btnUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrlActionPerformed(evt);
            }
        });

        lblSizeRect.setText("Size of Rectangle (pixels):");
        lblSizeRect.setEnabled(false);

        lblwxh.setText("width x height ");
        lblwxh.setEnabled(false);

        lblx.setText("x");
        lblx.setEnabled(false);

        txtWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWidth.setText("256");
        txtWidth.setEnabled(false);

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText("256");
        txtHeight.setEnabled(false);

        lblNGroups.setText("How many groups want to do?");

        txtNGroups.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNGroups.setText("2");

        lblQuestion.setText("Do you want to work with...");

        rbtnSquare.setText("...square selections?");

        rbtnScaled.setText("...scaled images?");
        rbtnScaled.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnScaledItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUrl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNGroups)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblQuestion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnScaled)
                            .addComponent(rbtnSquare)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblSizeRect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblwxh)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrl)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGroups)
                    .addComponent(txtNGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnScaled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSizeRect)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblwxh)
                    .addComponent(lblx))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrlActionPerformed
        int result;
        JFileChooser chooser = new JFileChooser();

        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Browse");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); //only open directories
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String dir = (chooser.getSelectedFile()).getPath();
            txtUrl.setText(dir);
        }
    }//GEN-LAST:event_btnUrlActionPerformed

    private void rbtnScaledItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnScaledItemStateChanged
        if (rbtnScaled.isSelected()) {
            this.lblSizeRect.setEnabled(true);
            this.txtWidth.setEnabled(true);
            this.txtHeight.setEnabled(true);
            this.lblwxh.setEnabled(true);
            this.lblx.setEnabled(true);
        } else {
            this.lblSizeRect.setEnabled(false);
            this.txtWidth.setEnabled(false);
            this.txtHeight.setEnabled(false);
            this.lblwxh.setEnabled(false);
            this.lblx.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnScaledItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUrl;
    private javax.swing.JLabel lblNGroups;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblSizeRect;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblwxh;
    private javax.swing.JLabel lblx;
    private javax.swing.JRadioButton rbtnScaled;
    private javax.swing.JRadioButton rbtnSquare;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtNGroups;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

//properties (get&set)
    public String getTxtUrl() {
        return this.txtUrl.getText();
    }

    public int getTxtWidth() {
        return Integer.parseInt(this.txtWidth.getText());
    }

    public int getTxtHeight() {
        return Integer.parseInt(this.txtHeight.getText());
    }

    public int getTxtNGroups() {
        if(txtNGroups.getText().isEmpty())
        {
            txtNGroups.setText("0");
        }
        return Integer.parseInt(this.txtNGroups.getText());
    }

    public boolean getRbtnSquare() {
        return this.rbtnSquare.isSelected();
    }

    public boolean getRbtnScaled() {
        return this.rbtnScaled.isSelected();
    }
}
